name: CI
on:
  - pull_request
jobs:
  composer-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          tools: composer:v2

      - name: Validate composer.json
        run: composer validate

  php-linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.1"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          tools: composer:v2

      - name: PHP lint
        run: "find *.php Classes Configuration Tests -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l"

  xml-linting:
    runs-on: ubuntu-latest
    needs:
      - composer-linting
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          tools: composer:v2

      - name: Install xmllint
        run: sudo apt-get install libxml2-utils

      - name: Setup composer
        run: |
          mkdir -p /home/runner/.config/composer/
          composer config -g github-oauth.github.com ${{ secrets.TOKEN }} -vvv

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: PHPUnit configuration file
        run: xmllint --schema vendor/phpunit/phpunit/phpunit.xsd --noout phpunit.xml.dist

      - name: Fetch schema for xliff
        run: wget https://docs.oasis-open.org/xliff/v1.2/os/xliff-core-1.2-strict.xsd --output-document=.Build/xliff-core-1.2-strict.xsd

      - name: TYPO3 language files
        run: xmllint --schema .Build/xliff-core-1.2-strict.xsd --noout $(find Resources -name '*.xlf')

  coding-guideline:
    runs-on: ubuntu-latest
    needs:
      - composer-linting
      - php-linting
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          tools: composer:v2

      - name: Setup composer
        run: |
          mkdir -p /home/runner/.config/composer/
          composer config -g github-oauth.github.com ${{ secrets.TOKEN }} -vvv

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Coding Guideline
        run: ./vendor/bin/ecs check

  code-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.1"
    needs:
      - composer-linting
      - php-linting
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          tools: composer:v2

      - name: Setup composer
        run: |
          mkdir -p /home/runner/.config/composer/
          composer config -g github-oauth.github.com ${{ secrets.TOKEN }} -vvv

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Code Quality (by PHPStan)
        run: ./vendor/bin/phpstan analyse

  rector:
    runs-on: ubuntu-latest
    needs:
      - composer-linting
      - php-linting
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          tools: composer:v2

      - name: Setup composer
        run: |
          mkdir -p /home/runner/.config/composer/
          composer config -g github-oauth.github.com ${{ secrets.TOKEN }} -vvv

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Rector
        run: ./vendor/bin/rector

  tests:
    runs-on: ubuntu-latest
    needs:
      - composer-linting
      - php-linting
      - xml-linting
    strategy:
      matrix:
        php-version:
          - "8.1"
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          tools: composer:v2

      - name: Setup composer
        run: |
          mkdir -p /home/runner/.config/composer/
          composer config -g github-oauth.github.com ${{ secrets.TOKEN }} -vvv

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: PHPUnit Tests
        run: ./vendor/bin/phpunit --testdox
